// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/paxos/paxos.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *PrepareRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PrepareResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AcceptedProposalId int64                  `protobuf:"varint,2,opt,name=accepted_proposal_id,json=acceptedProposalId,proto3" json:"accepted_proposal_id,omitempty"` // número da proposta aceita
	AcceptedValue      []byte                 `protobuf:"bytes,3,opt,name=accepted_value,json=acceptedValue,proto3" json:"accepted_value,omitempty"`                   // valor da proposta aceita
	ErrorMessage       string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                      // mensagem de erro, se houver
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareResponse) GetAcceptedProposalId() int64 {
	if x != nil {
		return x.AcceptedProposalId
	}
	return 0
}

func (x *PrepareResponse) GetAcceptedValue() []byte {
	if x != nil {
		return x.AcceptedValue
	}
	return nil
}

func (x *PrepareResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // número da proposta
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                  // chave do valor a ser aceito
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                              // valor a ser aceito
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *AcceptRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AcceptRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type AcceptResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                // indica se a aceitação foi bem-sucedida
	CurrentProposalId int64                  `protobuf:"varint,2,opt,name=current_proposal_id,json=currentProposalId,proto3" json:"current_proposal_id,omitempty"` // número da proposta aceita
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                   // mensagem de erro, se houver
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptResponse) GetCurrentProposalId() int64 {
	if x != nil {
		return x.CurrentProposalId
	}
	return 0
}

func (x *AcceptResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_paxos_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_paxos_proto_rawDesc = "" +
	"\n" +
	"\x17proto/paxos/paxos.proto\x12\x05paxos\"C\n" +
	"\x0ePrepareRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xa9\x01\n" +
	"\x0fPrepareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x14accepted_proposal_id\x18\x02 \x01(\x03R\x12acceptedProposalId\x12%\n" +
	"\x0eaccepted_value\x18\x03 \x01(\fR\racceptedValue\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"X\n" +
	"\rAcceptRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x7f\n" +
	"\x0eAcceptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13current_proposal_id\x18\x02 \x01(\x03R\x11currentProposalId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2x\n" +
	"\x05Paxos\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PrepareResponse\x125\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x15.paxos.AcceptResponseB6Z4github.com/luizgustavojunqueira/KV-Store-Paxos/paxosb\x06proto3"

var (
	file_proto_paxos_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_paxos_proto_rawDescData []byte
)

func file_proto_paxos_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_paxos_proto_rawDesc), len(file_proto_paxos_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_paxos_proto_rawDescData
}

var file_proto_paxos_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_paxos_paxos_proto_goTypes = []any{
	(*PrepareRequest)(nil),  // 0: paxos.PrepareRequest
	(*PrepareResponse)(nil), // 1: paxos.PrepareResponse
	(*AcceptRequest)(nil),   // 2: paxos.AcceptRequest
	(*AcceptResponse)(nil),  // 3: paxos.AcceptResponse
}
var file_proto_paxos_paxos_proto_depIdxs = []int32{
	0, // 0: paxos.Paxos.Prepare:input_type -> paxos.PrepareRequest
	2, // 1: paxos.Paxos.Accept:input_type -> paxos.AcceptRequest
	1, // 2: paxos.Paxos.Prepare:output_type -> paxos.PrepareResponse
	3, // 3: paxos.Paxos.Accept:output_type -> paxos.AcceptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_paxos_paxos_proto_init() }
func file_proto_paxos_paxos_proto_init() {
	if File_proto_paxos_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_paxos_proto_rawDesc), len(file_proto_paxos_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_paxos_proto_depIdxs,
		MessageInfos:      file_proto_paxos_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_paxos_proto = out.File
	file_proto_paxos_paxos_proto_goTypes = nil
	file_proto_paxos_paxos_proto_depIdxs = nil
}
