// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/paxos/paxos.proto

package paxos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_UNKNOWN CommandType = 0 // comando desconhecido
	CommandType_SET     CommandType = 1 // comando para definir um valor
	CommandType_DELETE  CommandType = 2 // comando para deletar um valor
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SET",
		2: "DELETE",
	}
	CommandType_value = map[string]int32{
		"UNKNOWN": 0,
		"SET":     1,
		"DELETE":  2,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paxos_paxos_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_paxos_paxos_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=paxos.CommandType" json:"type,omitempty"`        // tipo do comando
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                  // chave do valor a ser manipulado
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                              // valor a ser manipulado, se aplicável
	ProposalId    int64                  `protobuf:"varint,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // número da proposta associada ao comando
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_UNKNOWN
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Command) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // número da proposta
	SlotId        int64                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`             // número do slot da proposta
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *PrepareRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type PrepareResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                      // mensagem de erro, se houver
	AcceptedProposalId int64                  `protobuf:"varint,3,opt,name=accepted_proposal_id,json=acceptedProposalId,proto3" json:"accepted_proposal_id,omitempty"` // número da proposta aceita
	AcceptedCommand    *Command               `protobuf:"bytes,4,opt,name=accepted_command,json=acceptedCommand,proto3" json:"accepted_command,omitempty"`             // comando aceito, se houver
	CurrentProposalId  int64                  `protobuf:"varint,5,opt,name=current_proposal_id,json=currentProposalId,proto3" json:"current_proposal_id,omitempty"`    // número da proposta atual
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PrepareResponse) GetAcceptedProposalId() int64 {
	if x != nil {
		return x.AcceptedProposalId
	}
	return 0
}

func (x *PrepareResponse) GetAcceptedCommand() *Command {
	if x != nil {
		return x.AcceptedCommand
	}
	return nil
}

func (x *PrepareResponse) GetCurrentProposalId() int64 {
	if x != nil {
		return x.CurrentProposalId
	}
	return 0
}

type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"` // número da proposta
	SlotId        int64                  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`             // número do slot da proposta
	Command       *Command               `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                          // comando a ser aceito
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *AcceptRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AcceptRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AcceptResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                // indica se a aceitação foi bem-sucedida
	CurrentProposalId int64                  `protobuf:"varint,2,opt,name=current_proposal_id,json=currentProposalId,proto3" json:"current_proposal_id,omitempty"` // número da proposta aceita
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                   // mensagem de erro, se houver
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptResponse) GetCurrentProposalId() int64 {
	if x != nil {
		return x.CurrentProposalId
	}
	return 0
}

func (x *AcceptResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProposeLeaderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProposalId       int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`                  // Número da proposta para a eleição do líder
	CandidateAddress string                 `protobuf:"bytes,2,opt,name=candidate_address,json=candidateAddress,proto3" json:"candidate_address,omitempty"` // Endereço do candidato a líder
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProposeLeaderRequest) Reset() {
	*x = ProposeLeaderRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeLeaderRequest) ProtoMessage() {}

func (x *ProposeLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeLeaderRequest.ProtoReflect.Descriptor instead.
func (*ProposeLeaderRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *ProposeLeaderRequest) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *ProposeLeaderRequest) GetCandidateAddress() string {
	if x != nil {
		return x.CandidateAddress
	}
	return ""
}

type ProposeLeaderResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Success                        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage                   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                                              // Mensagem de erro, se houver
	CurrentHighestLeaderProposalId int64                  `protobuf:"varint,3,opt,name=current_highest_leader_proposal_id,json=currentHighestLeaderProposalId,proto3" json:"current_highest_leader_proposal_id,omitempty"` // Número da proposta do líder atual
	CurrentLeaderAddress           string                 `protobuf:"bytes,4,opt,name=current_leader_address,json=currentLeaderAddress,proto3" json:"current_leader_address,omitempty"`                                    // Endereço do líder atual
	HighestDecidedSlotId           int64                  `protobuf:"varint,5,opt,name=highest_decided_slot_id,json=highestDecidedSlotId,proto3" json:"highest_decided_slot_id,omitempty"`                                 // Slot mais alto decidido até o momento
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ProposeLeaderResponse) Reset() {
	*x = ProposeLeaderResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeLeaderResponse) ProtoMessage() {}

func (x *ProposeLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeLeaderResponse.ProtoReflect.Descriptor instead.
func (*ProposeLeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *ProposeLeaderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProposeLeaderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProposeLeaderResponse) GetCurrentHighestLeaderProposalId() int64 {
	if x != nil {
		return x.CurrentHighestLeaderProposalId
	}
	return 0
}

func (x *ProposeLeaderResponse) GetCurrentLeaderAddress() string {
	if x != nil {
		return x.CurrentLeaderAddress
	}
	return ""
}

func (x *ProposeLeaderResponse) GetHighestDecidedSlotId() int64 {
	if x != nil {
		return x.HighestDecidedSlotId
	}
	return 0
}

type LeaderHeartbeat struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LeaderAddress        string                 `protobuf:"bytes,1,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`                           // Endereço do líder
	CurrentProposalId    int64                  `protobuf:"varint,2,opt,name=current_proposal_id,json=currentProposalId,proto3" json:"current_proposal_id,omitempty"`            // Número da proposta atual do líder
	HighestDecidedSlotId int64                  `protobuf:"varint,3,opt,name=highest_decided_slot_id,json=highestDecidedSlotId,proto3" json:"highest_decided_slot_id,omitempty"` // Slot mais alto decidido até o momento
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LeaderHeartbeat) Reset() {
	*x = LeaderHeartbeat{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHeartbeat) ProtoMessage() {}

func (x *LeaderHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHeartbeat.ProtoReflect.Descriptor instead.
func (*LeaderHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderHeartbeat) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *LeaderHeartbeat) GetCurrentProposalId() int64 {
	if x != nil {
		return x.CurrentProposalId
	}
	return 0
}

func (x *LeaderHeartbeat) GetHighestDecidedSlotId() int64 {
	if x != nil {
		return x.HighestDecidedSlotId
	}
	return 0
}

type LeaderHeartbeatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                     // Indica se o heartbeat foi bem-sucedido
	ErrorMessage       string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                        // Mensagem de erro, se houver
	KnownHighestSlotId int64                  `protobuf:"varint,3,opt,name=known_highest_slot_id,json=knownHighestSlotId,proto3" json:"known_highest_slot_id,omitempty"` // Slot mais alto que o Acceptor/Learner conhece
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeaderHeartbeatResponse) Reset() {
	*x = LeaderHeartbeatResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderHeartbeatResponse) ProtoMessage() {}

func (x *LeaderHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*LeaderHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *LeaderHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaderHeartbeatResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LeaderHeartbeatResponse) GetKnownHighestSlotId() int64 {
	if x != nil {
		return x.KnownHighestSlotId
	}
	return 0
}

type LearnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int64                  `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // Número do slot que está sendo aprendido
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnRequest) Reset() {
	*x = LearnRequest{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnRequest) ProtoMessage() {}

func (x *LearnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnRequest.ProtoReflect.Descriptor instead.
func (*LearnRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *LearnRequest) GetSlotId() int64 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type LearnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decided       bool                   `protobuf:"varint,1,opt,name=decided,proto3" json:"decided,omitempty"` // Indica se o slot foi decidido
	Command       *Command               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`  // Comando associado ao slot, se decidido
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnResponse) Reset() {
	*x = LearnResponse{}
	mi := &file_proto_paxos_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnResponse) ProtoMessage() {}

func (x *LearnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnResponse.ProtoReflect.Descriptor instead.
func (*LearnResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *LearnResponse) GetDecided() bool {
	if x != nil {
		return x.Decided
	}
	return false
}

func (x *LearnResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_proto_paxos_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_paxos_proto_rawDesc = "" +
	"\n" +
	"\x17proto/paxos/paxos.proto\x12\x05paxos\"z\n" +
	"\aCommand\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.paxos.CommandTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\x03R\n" +
	"proposalId\"J\n" +
	"\x0ePrepareRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x03R\x06slotId\"\xed\x01\n" +
	"\x0fPrepareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x120\n" +
	"\x14accepted_proposal_id\x18\x03 \x01(\x03R\x12acceptedProposalId\x129\n" +
	"\x10accepted_command\x18\x04 \x01(\v2\x0e.paxos.CommandR\x0facceptedCommand\x12.\n" +
	"\x13current_proposal_id\x18\x05 \x01(\x03R\x11currentProposalId\"s\n" +
	"\rAcceptRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\x03R\x06slotId\x12(\n" +
	"\acommand\x18\x03 \x01(\v2\x0e.paxos.CommandR\acommand\"\x7f\n" +
	"\x0eAcceptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13current_proposal_id\x18\x02 \x01(\x03R\x11currentProposalId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"d\n" +
	"\x14ProposeLeaderRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12+\n" +
	"\x11candidate_address\x18\x02 \x01(\tR\x10candidateAddress\"\x8f\x02\n" +
	"\x15ProposeLeaderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12J\n" +
	"\"current_highest_leader_proposal_id\x18\x03 \x01(\x03R\x1ecurrentHighestLeaderProposalId\x124\n" +
	"\x16current_leader_address\x18\x04 \x01(\tR\x14currentLeaderAddress\x125\n" +
	"\x17highest_decided_slot_id\x18\x05 \x01(\x03R\x14highestDecidedSlotId\"\x9f\x01\n" +
	"\x0fLeaderHeartbeat\x12%\n" +
	"\x0eleader_address\x18\x01 \x01(\tR\rleaderAddress\x12.\n" +
	"\x13current_proposal_id\x18\x02 \x01(\x03R\x11currentProposalId\x125\n" +
	"\x17highest_decided_slot_id\x18\x03 \x01(\x03R\x14highestDecidedSlotId\"\x8b\x01\n" +
	"\x17LeaderHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x121\n" +
	"\x15known_highest_slot_id\x18\x03 \x01(\x03R\x12knownHighestSlotId\"'\n" +
	"\fLearnRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\x03R\x06slotId\"S\n" +
	"\rLearnResponse\x12\x18\n" +
	"\adecided\x18\x01 \x01(\bR\adecided\x12(\n" +
	"\acommand\x18\x02 \x01(\v2\x0e.paxos.CommandR\acommand*/\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03SET\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x022\xc1\x02\n" +
	"\x05Paxos\x128\n" +
	"\aPrepare\x12\x15.paxos.PrepareRequest\x1a\x16.paxos.PrepareResponse\x125\n" +
	"\x06Accept\x12\x14.paxos.AcceptRequest\x1a\x15.paxos.AcceptResponse\x12J\n" +
	"\rProposeLeader\x12\x1b.paxos.ProposeLeaderRequest\x1a\x1c.paxos.ProposeLeaderResponse\x12G\n" +
	"\rSendHeartbeat\x12\x16.paxos.LeaderHeartbeat\x1a\x1e.paxos.LeaderHeartbeatResponse\x122\n" +
	"\x05Learn\x12\x13.paxos.LearnRequest\x1a\x14.paxos.LearnResponseB6Z4github.com/luizgustavojunqueira/KV-Store-Paxos/paxosb\x06proto3"

var (
	file_proto_paxos_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_paxos_proto_rawDescData []byte
)

func file_proto_paxos_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_paxos_proto_rawDesc), len(file_proto_paxos_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_paxos_proto_rawDescData
}

var file_proto_paxos_paxos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_paxos_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_paxos_paxos_proto_goTypes = []any{
	(CommandType)(0),                // 0: paxos.CommandType
	(*Command)(nil),                 // 1: paxos.Command
	(*PrepareRequest)(nil),          // 2: paxos.PrepareRequest
	(*PrepareResponse)(nil),         // 3: paxos.PrepareResponse
	(*AcceptRequest)(nil),           // 4: paxos.AcceptRequest
	(*AcceptResponse)(nil),          // 5: paxos.AcceptResponse
	(*ProposeLeaderRequest)(nil),    // 6: paxos.ProposeLeaderRequest
	(*ProposeLeaderResponse)(nil),   // 7: paxos.ProposeLeaderResponse
	(*LeaderHeartbeat)(nil),         // 8: paxos.LeaderHeartbeat
	(*LeaderHeartbeatResponse)(nil), // 9: paxos.LeaderHeartbeatResponse
	(*LearnRequest)(nil),            // 10: paxos.LearnRequest
	(*LearnResponse)(nil),           // 11: paxos.LearnResponse
}
var file_proto_paxos_paxos_proto_depIdxs = []int32{
	0,  // 0: paxos.Command.type:type_name -> paxos.CommandType
	1,  // 1: paxos.PrepareResponse.accepted_command:type_name -> paxos.Command
	1,  // 2: paxos.AcceptRequest.command:type_name -> paxos.Command
	1,  // 3: paxos.LearnResponse.command:type_name -> paxos.Command
	2,  // 4: paxos.Paxos.Prepare:input_type -> paxos.PrepareRequest
	4,  // 5: paxos.Paxos.Accept:input_type -> paxos.AcceptRequest
	6,  // 6: paxos.Paxos.ProposeLeader:input_type -> paxos.ProposeLeaderRequest
	8,  // 7: paxos.Paxos.SendHeartbeat:input_type -> paxos.LeaderHeartbeat
	10, // 8: paxos.Paxos.Learn:input_type -> paxos.LearnRequest
	3,  // 9: paxos.Paxos.Prepare:output_type -> paxos.PrepareResponse
	5,  // 10: paxos.Paxos.Accept:output_type -> paxos.AcceptResponse
	7,  // 11: paxos.Paxos.ProposeLeader:output_type -> paxos.ProposeLeaderResponse
	9,  // 12: paxos.Paxos.SendHeartbeat:output_type -> paxos.LeaderHeartbeatResponse
	11, // 13: paxos.Paxos.Learn:output_type -> paxos.LearnResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_paxos_paxos_proto_init() }
func file_proto_paxos_paxos_proto_init() {
	if File_proto_paxos_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_paxos_proto_rawDesc), len(file_proto_paxos_paxos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_paxos_proto_depIdxs,
		EnumInfos:         file_proto_paxos_paxos_proto_enumTypes,
		MessageInfos:      file_proto_paxos_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_paxos_proto = out.File
	file_proto_paxos_paxos_proto_goTypes = nil
	file_proto_paxos_paxos_proto_depIdxs = nil
}
